apiVersion: v1
kind: ConfigMap
metadata:
  name: elevatelearning-config
  namespace: elevatelearning
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_ENGINE: "django.db.backends.mysql"
  DB_NAME: "elevatelearning_db"
  DB_USER: "djangouser"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  CSRF_TRUSTED_ORIGINS: "http://34.87.248.125"
---
apiVersion: v1
kind: Secret
metadata:
  name: elevatelearning-secret
  namespace: elevatelearning
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-this-in-production-xyz123"
  DB_PASSWORD: "djangopassword123"
  MYSQL_ROOT_PASSWORD: "rootpassword123"
